services:
  - type: web
    name: bot-time-boss-l2
    env: python
    plan: free
    buildCommand: ""
    startCommand: python bossrespawn.py
    buildFilter:
      paths:
        - runtime.txt
        - requirements.txt
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
